# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GeneralError(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'int',
        'fields': 'str',
        'message': 'str'
    }

    attribute_map = {
        'code': 'code',
        'fields': 'fields',
        'message': 'message'
    }

    def __init__(self, code=None, fields=None, message=None):
        """
        GeneralError - a model defined in Swagger
        """

        self._code = None
        self._fields = None
        self._message = None

        if code is not None:
          self.code = code
        if fields is not None:
          self.fields = fields
        if message is not None:
          self.message = message

    @property
    def code(self):
        """
        Gets the code of this GeneralError.

        :return: The code of this GeneralError.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this GeneralError.

        :param code: The code of this GeneralError.
        :type: int
        """

        self._code = code

    @property
    def fields(self):
        """
        Gets the fields of this GeneralError.

        :return: The fields of this GeneralError.
        :rtype: str
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """
        Sets the fields of this GeneralError.

        :param fields: The fields of this GeneralError.
        :type: str
        """

        self._fields = fields

    @property
    def message(self):
        """
        Gets the message of this GeneralError.

        :return: The message of this GeneralError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this GeneralError.

        :param message: The message of this GeneralError.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GeneralError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
