# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SubscribedCrop(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country_iso': 'str',
        'name': 'str'
    }

    attribute_map = {
        'country_iso': 'country_iso',
        'name': 'name'
    }

    def __init__(self, country_iso=None, name=None):
        """
        SubscribedCrop - a model defined in Swagger
        """

        self._country_iso = None
        self._name = None

        if country_iso is not None:
          self.country_iso = country_iso
        if name is not None:
          self.name = name

    @property
    def country_iso(self):
        """
        Gets the country_iso of this SubscribedCrop.
        Crop country ISO

        :return: The country_iso of this SubscribedCrop.
        :rtype: str
        """
        return self._country_iso

    @country_iso.setter
    def country_iso(self, country_iso):
        """
        Sets the country_iso of this SubscribedCrop.
        Crop country ISO

        :param country_iso: The country_iso of this SubscribedCrop.
        :type: str
        """

        self._country_iso = country_iso

    @property
    def name(self):
        """
        Gets the name of this SubscribedCrop.
        Crop name

        :return: The name of this SubscribedCrop.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SubscribedCrop.
        Crop name

        :param name: The name of this SubscribedCrop.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SubscribedCrop):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
