# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Table(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'columns': 'list[ColumnDescription]',
        'data': 'list[TableRow]'
    }

    attribute_map = {
        'columns': 'columns',
        'data': 'data'
    }

    def __init__(self, columns=None, data=None):
        """
        Table - a model defined in Swagger
        """

        self._columns = None
        self._data = None

        if columns is not None:
          self.columns = columns
        if data is not None:
          self.data = data

    @property
    def columns(self):
        """
        Gets the columns of this Table.

        :return: The columns of this Table.
        :rtype: list[ColumnDescription]
        """
        return self._columns

    @columns.setter
    def columns(self, columns):
        """
        Sets the columns of this Table.

        :param columns: The columns of this Table.
        :type: list[ColumnDescription]
        """

        self._columns = columns

    @property
    def data(self):
        """
        Gets the data of this Table.

        :return: The data of this Table.
        :rtype: list[TableRow]
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this Table.

        :param data: The data of this Table.
        :type: list[TableRow]
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Table):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
