# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kernel_api_client
from kernel_api_client.rest import ApiException
from kernel_api_client.apis.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """ TokenApi unit test stubs """

    def setUp(self):
        self.api = kernel_api_client.apis.token_api.TokenApi()

    def tearDown(self):
        pass

    def test_token_post(self):
        """
        Test case for token_post

        Auth Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
