# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.timeseries import Timeseries


class TestTimeseries(unittest.TestCase):
    """ Timeseries unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeseries(self):
        """
        Test Timeseries
        """
        model = swagger_client.models.timeseries.Timeseries()


if __name__ == '__main__':
    unittest.main()
