# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.geography import Geography


class TestGeography(unittest.TestCase):
    """ Geography unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeography(self):
        """
        Test Geography
        """
        model = swagger_client.models.geography.Geography()


if __name__ == '__main__':
    unittest.main()
