# coding: utf-8

"""
    Kernel API

    Access Kernel insights programmatically

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kernel_api_client
from kernel_api_client.rest import ApiException
from kernel_api_client.apis.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """ MetricsApi unit test stubs """

    def setUp(self):
        self.api = kernel_api_client.apis.metrics_api.MetricsApi()

    def tearDown(self):
        pass

    def test_forecasts_metadata_get(self):
        """
        Test case for forecasts_metadata_get

        Forecast model metadata
        """
        pass

    def test_metrics_metadata_get(self):
        """
        Test case for metrics_metadata_get

        All available metric names and descriptions
        """
        pass

    def test_metrics_table_get(self):
        """
        Test case for metrics_table_get

        Get values for a metric (or group of metrics) for a specific geography, crop, and date (or date range).
        """
        pass


if __name__ == '__main__':
    unittest.main()
